# Enable tab completion
source ~/git-completion.bash

# colors!
green="\[\033[01;32m\]"
blue="\[\033[01;34m\]"
purple="\[\033[01;35m\]"
reset="\[\033[0m\]"

# Change command prompt
source ~/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1
# '\u' adds the name of the current user to the prompt
# '\$(__git_ps1)' adds git-related stuff
# '\w' adds the path to the current directory
export PS1="$purple\u$blue \w$green\$(__git_ps1) $ $reset"
